### PR TITLE
Don't automatically remove commands

### LINKED ISSUE #156: Visual Studio for Mac crashes when opening Edit menu
Every time I try to open Edit menu, Visual Studio crashes, when at least one source code file is open. 
(VS version 7.2 build 487, but I don't think it matters)

It looks like the culprit is the following line:
https://github.com/nosami/XSVim/blob/7.0/XSVim/XSVim.fs#L43
It was introduced in this commit: https://github.com/nosami/XSVim/commit/bb69ad6bb166691f2d7e7e4c7708c7d7e8ec5d36. If I comment out `"Control+I"` then the crashes do not happen.

This could be because I manually reassigned `CTRL-I` to "Format Document", which is the default binding. I tried removing the binding using VS's Preferences dialog, but still got the crashes.

*Side note:*
I'm not convinced we should disable `CTRL-I` *automatically*. This is out-of-the-box binding to one of the most frequently used commands.

### PR DESCRIPTION
**Pull request by nosami**
Fixes #156

Create commands for all keybinds that may conflict with built in keybinding
schemes (Just Visual Studio for Mac default for now).

Also created Visual Studio + Vim keybinding scheme to set vim keys for users
that want that behaviour.

### CODE REVIEW

**Comment by nosami** [comment]
Binding scheme
image

**Comment by nosami** [comment]
If the Vim keys don't conflict with any of the current scheme's bindings, then the vim keys work as before without any modifications required.

With the new Vim keybinding scheme applied, the conflicting keys in the current scheme are set to an empty string and the Vim keys are applied. This can be reverted by switching the keybinding scheme back to whatever it was previously.

Downsides to this are that the Vim keys aren't enabled by default and it might not be obvious to a new user how to make these keys work. Also, the Vim keys that are mapped to commands now work in any mode - the control keys modified in the screenshot should only work in normal mode, but this probably isn't an issue.

**Comment by shirshov** [comment]
This commit does indeed fix #156. CTRL-I works as "Format Document", which is the default binding.

However, it seems to break other stuff when using "Visual Studio + VIM" scheme. E.g. pressing CTRL-I moves focus to search field (upper left), although it is set to "VIM / Navigate Forwards"

**Comment by nosami** [comment]
@shirshov Thanks for checking - I'll take a look at CTRL-I

**Pull request merged**
