### PR TITLE
Handling for nested braces. Fixes #22

### LINKED ISSUE #22: `vi)` doesn't support nested parentheses
Where `#` is the cursor

`((abc)de#f)`
type `vi)`

The selection becomes contains `abc)def`, but it should contain `(abc)def`

Similarly, if you do a `yi)`, it will only yank `abc)def`

### PR DESCRIPTION
**Pull request by shirshov**

### CODE REVIEW

**Comment by shirshov** [comment]
Hmm... This _doesn't work_. All the tests pass, but when trying it in the VS on _code (F#, C#)_ none of the commands for working with braces work. XSVim switches to insert mode and that's all. Works in a text file though. I have no idea why...

**Comment by shirshov** [comment]
Found the problem with the algorithm, will reopen when fixed.

**Comment by shirshov** [comment]
Fixed now, ready to merge.

**Comment by nosami** [comment]
Nice work - thanks!

**Pull request merged**
